# API 리다이렉트
[[redirects]]
  from = "/api/*"
  to = "${VITE_API_URL}/api/:splat"
  status = 200
  force = true
  headers = {
    X-Redirect-Info = "Redirected by Netlify"
  }
  
# SPA 라우팅을 위한 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200